min_version = "2026.6"

#
# -- fancy stuff --
#
[tools]
usage = "latest"
starship = "latest"
bat = "latest"
neovim = "latest"
tmux = "3.6a"
fzf = "latest"
eza = "latest"
fd = "latest"
ripgrep = "latest"
zoxide = "latest"
btop = "latest"
difftastic = "latest"
shfmt = "latest"
fastfetch = "latest"
shellcheck = "latest"
lazygit = "latest"
#
# -- devops stuff --
#
task = "latest"
kubie = "latest"
sops = "latest"
age = "latest"
terragrunt = "latest"
# flux2 = "2.7"
kubectl = "1.35"
k9s = "latest"

# vault = "1.20"
# terraform = "1.13"
# helm = "3.19"
opentofu = "latest"
# jq = "1.8"
#

# -- packaging stuff --
#
pipx = "latest"

#
# -- programming languages --
#
node = "latest"
python = "3.14"
go = "latest"
rust = "stable"

[env]
SOPS_EDITOR = "nvim"

[settings]
experimental = true
